### ISSUE TITLE
Index required for OAuth Applications

### ISSUE THREAD

**Issue by stakach** [PlaceOS/rubber-soul#1]
This route: http://localhost:8080/api/engine/v2/oauth_apps?bearer_token=
returns 
```
ERROR: ES error: 404
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [doorkeeper_app]"
```
The model is: https://github.com/PlaceOS/models/blob/master/src/models/doorkeeper_application.cr

Additionally we need indexes for:
* LdapAuthentication (ldap_strat)
* OAuthAuthentication (oauth_strat)
* SamlAuthentication  (adfs_strat)

This is required for PlaceOS/backoffice#5

**Comment by caspiano** [comment]
Implemented in commit ab2a612557f8ad578309f229eb40dcd749eecd5d
