### ISSUE TITLE
BUG: regression in index creation

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/rubber-soul#15]
Regression introduced from bf5fda182ff9adc71369aba3282e29112f93dbfb onwards.
It appears that some indexes are not created when reindexing or starting up.

**Comment by jeremyw24** [comment]
@caspiano can I get an update on this issue, close if no longer relevant.

**Comment by caspiano** [comment]
Haven't observed this issue since.
Likely a misalignment of models across the application, our release process remedies this kind of issue.
